my_string = input('В каком городе вы проживаете? ')
print(len(my_string))
print('В каком городе вы проживаете?'.upper())
print('В каком городе вы проживаете?'.lower())
print('В каком городе вы проживаете?'.replace(' ', ''))
print(my_string[:1:])
print(my_string[-1::])